Question 1

In [3]:
# printing an array from 2 - 50 with a step size of 3

import numpy as np
print(np.arange(2,51,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Question 2

In [ ]:
# Accept 2 lists each of 5 elements and convert it into numpy array and concatenate and sort the array

list1 = []
list2 = []
for i in range(5):
    list1.append(int(input()))
for j in range(5):
    list2.append(int(input()))
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.concatenate((arr1, arr2))
print(arr3)
arr = np.sort(arr3)
print(arr)

Question 3

In [ ]:
# create an array and find its dimension and size.

arr = np.array([[1,2,3],[7,8,9],[4,5,6]])
print(arr.ndim)
print(arr.size)

Question 4

In [ ]:
# code snippet to convert 1D array to 2D array using np.newaxis, np.expand_dims.

# using np.newaxis
arr = np.array([1,3,2,8,9,10,4,6,5])
print(arr)
print(arr.shape)
arr1 = arr[:, np.newaxis]
print(arr1)
print(arr1.shape)
arr2 = arr[np.newaxis, :]
print(arr2)
print(arr2.shape)

In [ ]:
# using np.expand_dims 

x = np.ones((4, 4))
print(x)
print(x.shape)
y = np.expand_dims(x, axis=1)
print(y)
print(y.shape)

Question 5

In [6]:
# Consider two square arrays and stack them vertically and horixontally

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,4,6],[8,10,12]])
print(np.hstack((x,y)))
print(np.vstack((x,y)))

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 2  4  6]
 [ 8 10 12]]


Question 6

In [ ]:
# to get unique items and to count it

arr = np.array([1,1,1,1,3,3,2,2,4,5,67,89,900,00,100,100,4])
unique,count =np.unique(arr,return_counts=True)
print('unique elements are ',unique)
print('Counts of the above elements are in the same order',count) 